---

board:
  width: 200
  height: 200

initial_populations:
  - number: 100
    position:
      strategy: random
      seed: 2
  - number: 100
    position:
      strategy: circle
      radius: 25
      point:
        x: 100
        y: 100
