---

position_strategies:
  random:
    module: position_strategies
    class: RandomPositionStrategy
  horizontal:
    module: position_strategies
    class: HorizontalPositionStrategy
  vertical:
    module: position_strategies
    class: VerticalPositionStrategy
  circle:
    module: position_strategies
    class: CirclePositionStrategy

board:
  width: 200
  height: 200

initial_populations:
  - count: 500
    genes:
      species: [1, 0, 0]
    position:
      strategy: circle
      radius: 25
      point:
        x: 25
        y: 25
  - count: 500
    genes:
      species: [0, 1, 0]
    position:
      strategy: circle
      radius: 25
      point:
        y: 174
        x: 25
  - count: 500
    genes:
      species: [0, 0, 1]
    position:
      strategy: circle
      radius: 25
      point:
        x: 174
        y: 174
  - count: 500
    genes:
      species: [1, 1, 0]
    position:
      strategy: circle
      radius: 25
      point:
        x: 174
        y: 25
  - count: 500
    genes:
      species: [0, 1, 1]
    position:
      strategy: circle
      radius: 25
      point:
        x: 100
        y: 100
    genes:
      strength: [1, 1, 1, 1, 1]
      mobility: [1, 1, 1, 1, 1]
      temperament: [1, 1, 1, 1, 1]
      max_energy: [1, 1, 1, 1, 1]
  - count: 15000
    position:
      strategy: random
    genes:
      max_age: [0, 0, 0, 0, 0]
      mobility: [0, 0, 0, 0, 0]
      strength: [0, 0, 0, 0, 0]
      max_energy: [1, 1, 1, 1, 1]
